::: {.author-block}
**Author:** Guangchuang Yu  
**Email:** <guangchuangyu@gmail.com>  
**Affiliation:** Department of Bioinformatics,  
School of Basic Medical Sciences, Southern Medical University  
**Date:** `r format(Sys.Date())`
:::

# Introduction

```{r}
#| include: false
library(yulab.utils)
Biocpkg <- yulab.utils::Biocpkg
```

epiSeeker is an R package for analyzing multi-omics epigenetic data. 
Data of fragment type, like ChIP-seq data and ATAC-seq data, are supported by epiSeeker. 
It supports annotating ChIP peaks and provides functions to visualize ChIP peaks coverage over chromosomes and 
profiles of peaks binding to TSS regions. 
Comparison of ChIP peak profiles and annotation are also supported. 
Moreover, it supports evaluating significant overlap among ChIP-seq datasets. 
Currently, it contains 17,000 bed file information from GEO database. 
These datasets can be downloaded and compare with user's own data to explore significant overlap datasets for 
inferring co-regulation or transcription factor complex for further investigation. 
Data of base type, like oxBS‑seq data, are also supported. 
It provides function to visualize single-base resolution epigenetic data by considering the strand, motif, and additional information. 

Biology relies heavily on epigenetics as a method of altering genetic information without altering nucleic acids. 
Based on the type of epigenomic data can be divided into two types: (1) fragment type, (2) base type.

Chromatin immunoprecipitation followed by high-throughput sequencing (ChIP-seq) is an canonical fragment type data. 
It has become standard technologies for genome wide identification of DNA-binding protein target sites. 
After read mappings and peak callings, the peak should be annotated to answer the biological questions. 
Annotation also create the possibility of integrating expression profile data to predict gene expression regulation. 
`r Biocpkg("ChIPseeker")`[@yu_chipseeker_2015] was developed for annotating nearest genes and genomic features to peaks.
ChIP peak data set comparison is also very important. We can use it as an index to estimate how well biological replications are. 
Even more important is applying to infer cooperative regulation. 
If two ChIP seq data, obtained by two different binding proteins, overlap significantly, 
these two proteins may form a complex or have interaction in regulation chromosome remodelling or gene expression. 
`r Biocpkg("ChIPseeker")`[@yu_chipseeker_2015] support statistical testing of significant overlap among ChIP seq data sets, 
and incorporate open access database GEO for users to compare their own dataset to those deposited in database. 
Protein interaction hypothesis can be generated by mining data deposited in database. 
Converting genome coordinations from one genome version to another is also supported, 
making this comparison available for different genome version and different species.
Several visualization functions are implemented to visualize the coverage of the ChIP seq data, peak annotation, 
average profile and heatmap of peaks binding to TSS region.
Functional enrichment analysis of the peaks can be performed by my Bioconductor packages 
`r Biocpkg("DOSE")`[@yu_dose_2015], `r Biocpkg("ReactomePA")`[@yu_reactomepa_2016], 
`r Biocpkg("clusterProfiler")`[@yu_clusterprofiler_2012].

Epigenomic data of base type refer to epigenomic modification at a single-base resolution. 
Many methods are used to detect the epigenetic status with the combination of sequencing and chemical methods, 
such as `Me‑DIP` and `oxBS‑seq` for `5mC`; `TAB-seq` and `hme‑DIP` for `5hmC`; `6mA‑DIP` and `6mA‑RE-seq` for `6mA`. 
Aside from these, third-generation sequencing methods, which refer to direct single-molecule sequencing, 
such as Oxford Nanopore Sequencing and PacBio SMRT Sequencing.

If you use `r Biocpkg("ChIPseeker")`[@yu_chipseeker_2015] in published research, please cite:

+ Q Wang<sup>#</sup>, M Li<sup>#</sup>, T Wu, L Zhan, L Li, M Chen, W Xie, Z Xie, E Hu, S Xu, __G Yu__<sup>\*</sup>. [Exploring epigenomic datasets by ChIPseeker](https://onlinelibrary.wiley.com/share/author/GYJGUBYCTRMYJFN2JFZZ?target=10.1002/cpz1.585). __*Current Protocols*__, 2022, 2(10): e585. 
+ __G Yu__<sup>\*</sup>, LG Wang, QY He<sup>\*</sup>. [ChIPseeker: an R/Bioconductor package for ChIP peak annotation, comparision and visualization](http://bioinformatics.oxfordjournals.org/cgi/content/abstract/btv145). __*Bioinformatics*__. 2015, 31(14):2382-2383. 
